kind: pipeline
type: docker
name: default


steps:
- name: Hello World
  image: centos
  commands:
    - echo Hello World
- name: build
  image: golang
  commands:
    - go env -w GO111MODULE=on
    - go env -w GOPROXY="https://goproxy.cn,direct"
    - go build -o main main.go

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
      auto_tag: true
      repo: uniquestudio/open-platform

trigger:
  branch:
    - test
