kind: pipeline
type: docker
name: default


steps:
- name: Hello World
  image: centos
  commands:
    - echo Hello World

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password
      auto_tag: true
      repo: uniquestudio/open-platform

trigger:
  branch:
    include:
    - test
    - rebuild
    - master
