name: CI
on:
  push:
    branches:
      - dev
    tags:
      - v*.*.*
jobs:
  Deploy-Dev:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/dev')
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKER_TOKEN }}
      - name: Set Git tag
        run: echo "RELEASE_VERSION=latest" >> $GITHUB_ENV
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ccr.ccs.tencentyun.com/unique-studio/open-platform:${{ env.RELEASE_VERSION }}
      - name: Install Ssh Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          # this step is necessary 
          known_hosts: unnecessary
      - name: add known hosts
        run: ssh-keyscan -p 22 -H ${{ secrets.SSH_IP }}  >> ~/.ssh/known_hosts

      - name: deploy by docker compose
        run: docker -H ${{ secrets.SSH_DSN }} compose up --remove-orphans

  Deploy-Prod:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKER_TOKEN }}
      - name: Set Git tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ccr.ccs.tencentyun.com/unique-studio/uniquesso:${{ env.RELEASE_VERSION }}